[package]
name = "day_05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prelude = { version = "0.1.0", path = "../prelude" }

[dev-dependencies]
env_logger = "0.10.1"
